### ISSUE TITLE
Give the input form field a name so browsers can remember auto-fill values

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#401]
This could speed up the genre task immensely! It could work for quite a few title tasks (except they're going to a textarea and that won't work?), but it's probably best not to put it on the date task field.

**Comment by alexandermendes** [comment]
Look at all form fields throughout the site at the same time - set `inputName` for vue-form-generator (see https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html).

**Comment by alexandermendes** [comment]
After some investigation it turns out that this isn't a totally straightforward issue. Setting the name attribute basically won't work properly for forms that are submitted via AJAX. At lease, not without some unreliable hacks...

https://stackoverflow.com/questions/9201858/how-to-store-to-browser-auto-complete-auto-fill-when-using-ajax-calls/9225091
https://stackoverflow.com/questions/15462991/trigger-autocomplete-without-submitting-a-form/30584602#30584602
https://stackoverflow.com/questions/1622628/browser-autocomplete-saved-form-not-work-in-ajax-request

Have made some changes so that the form will remember the first value entered when the project is loaded but can't get it to remember subsequent values without more work, probably writing some kind of autocomplete lookup function on the backend, not sure if that's feasible right now.

**Comment by mialondon** [comment]
@alexandermendes ah well, it was worth a try! Thanks for your work on it.
