### ISSUE TITLE
Finding task data

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#554]
I've looked at all the variations of the csv/json files for tasks, task runs and results, but I can't seem to find e.g. actual titles or dates. And if I can't, I doubt a more casual user could. 

a) where should I be looking?
b) what documentation or instructions need to be added to the data download page to make it more accessible?

**Comment by alexandermendes** [comment]
Sure, so the data page content is now editable via the interface and we can expand that easily, so this probably becomes a note for expanding the content rather than actual code changes. If you go for the "Task Run" data you'll find all of the contributions so far. I'll write the analysis functions to collate our transcriptions into the final results data this week.

**Comment by alexandermendes** [comment]
Would suggest that this one moves to the Trello board - not a code fix!

**Comment by alexandermendes** [comment]
Closing as there isn't anything left to do here!
