### ISSUE TITLE
Add user tags for tasks to enable shared image albums

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#631]
See https://community.libcrowds.com/d/21-conjurers-and-magicians/2

To be searched via https://github.com/Scifabric/pybossa/pull/1782

**Comment by alexandermendes** [comment]
It would also be cool to then generate a IIIF manifest for these user-generated albums so that they can be shared via whatever IIIF viewer.

**Comment by alexandermendes** [comment]
The like button is probably being removed when these customisable tags are added. We have a big enough sample now to check if there is any value in keeping this like button.

If anyone has used the like button up until now perhaps we should transform those likes into a "liked" tag.

**Comment by alexandermendes** [comment]
Yep, It hasn't.

Well, apart from by me and [this person](https://www.libcrowds.com/api/user/372) 😉

**Comment by Addaci** [comment]
MarineLives & Signs of Literacy (our new community to study historical literacy: http://signsofliteracy.org/) is doing some serious thinking about creating IIIF manifests to display markes, initials and signatures contained in manuscript pages. The functionality we are interested in is to be able to display text areas (or image areas) within a manuscript image and/or its matching full text transcription which contain relevant markes, initials and signatures, as well as to display the whole image page or whole matching full text transcription page. We want to be able to create IIIF manifests, which will pull up relevant markes, initials and signatures from multiple institutions with IIIF servers and content. For example the British Library and the Stadsarchief Amsterdam.

We are thinking how to semantically annotate or tag the images or text pages, and the specific image or text regions within the whole pages, so that manifests can be created.

The sort of tags or annotations we are thinking of are simple

e.g. Occupation [wine cooper; mariner; shipwright]
e.g. Type of signoff [marke; initial(s); signature]
e.g. Place of residence [e.g. Wapping; Cadiz]
e.g. Date of signoff [e.g. March 13th, 1629]

A specific signoff (marke, initial or signature) could have multiple tages, e.g. Text reading "Jo Bloggs, mariner, living in Wapping, aged 23" in a deposition dated March 13th 1629 could be tagged

mariner; Wapping; age 23; 1629
Our application envisages dealing with tens of thousands of legal records from the English High Court of Admiralty (TNA) and the Amsterdam notarial archives (Stadsarchief Amsterdam). Probably a minimum of 50,000 images, but could be many more.

We want to be able to crowdsource the tagging of the signoffs, having used Transkribus (or some other technology) to create an XML pixel level map of where the signoff is on the page of the manuscript.

Prior to crowdsourcing this tagging, we would want to take all the admiralty court and notarial images and upload them to one or more IIIF servers.

That's how far we have got. I have had an initial discussion with Digirati about this, but have parked the discussion for the moment, lacking funding. I will be giving a paper at the IIIF Washington DC conference, May 21-25th, at which I will be laying out a vision for greater integration of IIIF and Transkribus ecosystems, and making a pitch for the development of the above functionality I have described.

I would be very interested to hear your thoughts on this, and to see what sort of design solutions you come up with. I also have some interest from the Technical Director of Pelagios/Recogito, Rainer Simon at the Austrian Institute of Technology, for this sort of functionality.

Best wishes, Colin

**Comment by Addaci** [comment]
A second related idea we are looking at is user created shareable tag driven IIIF manifests. User created as opposed to project or archival created, though these are also important. Would probably want an authorship label in the manifest metadata to show author.

Users LOVE personal and themed boards. Witness Pinterest. But our concept is to make the boards or manifests independent of viewing platform. So you could view through any IIIF compatible viewer, such as Universal Viewer or Mirador, niot be forced to cut and paste your favourite playbills from LibCrowds. Your tags and ideally your and other people's semantic annotations would be available through your chosen IIIF viewer for interrogation.

* BL; Stadsarchief Amsterdam; Jo Bloggs

How would it work? Here is an example: a user could select the tags:

* lighterman + thames + wapping + signoff

This would generate a manifest containing all IIIF served images containing those tags. 

We would have a simple pre-specified ontology of tags. In this case lighterman is in the class of the tag ocupation; thames is in the class of the tag place of work; wapping is in the class of the tag place of residence; signoff is a class tag.

The class tag signoff would contain four primary component or base tags. They would be

* marke; initial; initials; signature

The ontology of the place of residence class tag is more complex, since in our case it needs to allow for 

* streets; sub-parish; parish; town/city; county; region; country; continent [ignoring for the moment the need to handle different geographic nesting structures in different countries]

Because Signs of  Literacy intends to be a comparative multi-country user driven community with multiple archival contributors of images and a mixture of general public and academic users, we need to think carefully about the conceptual design of the above.

We also need to think through the relationship between tags and annotations. As we engage with IIIF consortium, with the help if IIIF technical cordinator Glen Robson and with the help of the Recogito annotation platform team, we hope to develop this thinking.

We would love to involve LibCrowds in this discussion and to learn from your experience and experimentation with tag driven IIIF manifests.

I would be delighted to include tag driven IIIF manifests as a specific discussion point on the agenda of our technical tools for exploring historical literacy workshop on June 5th 2018 in Amsterdam.

**Comment by Addaci** [comment]
**@alexandermendes @mialondon @christianalgar We at MarineLives/Signs of Literacy would be interested in a conversation about BL's/our own proposed functionality for user tags to enable shared IIIF image albums, both in the short term and in the medium/longer term.**

- Core to our Signs of Literacy long term plans to apply machine learning in the study of historical literacy is to create large scale training data sets and control data sets. Both data sets will require large scale markup of images, both regions on the images containing markes, initials and signatures, and regions on the images containing metadata for person name, occupation, place of residence and date of deposition.

**- Core to our plans is also the use of crowdsourcing to tag and/or annotate the training and control data sets. Hence our strong interest in LibCrowds as a IIIF compliant crowdsourcing platform with a strong development team and multiple use cases from catalogues to playbills.**

**Proposition**

_Short term_

- MarineLives/Signs of Literacy piggy back onto your implementation of user tasks to enable shared image albums (IIIF manifests). We can't offer short term funding, but we would be happy to contribute to design ideas, possibly with some technical input from the Recogito technical team, and to user test your functionality using your Play Bills use case or any other use case you want to test.

- Using our own resource, we would create a very small demo of the functionality you develop (using our own use case of markes, initials and images). We would use in the order of twenty images from High Court of Admiralty data and twenty images from Alle Amsterdamser Akten data, which we would markup and tag using LibCrowds. Easiest would be on your server, though potentially we could implement our own server, but we would have to look at what would be required on the backend. (It is possible that the Recogito technical team would donate some technical time to do this for us; Digirati are also a possibility, though I would have to pay them). 

- We could demo something at the IIIF Washington conference, in late May 2018, with full acknowledgement to the BL., to supplement our broad vision of IIIF enablement and the use of IIIF compliant crowdsourcing to explore historical literacy. Alternatively, we could demo at our June 5th , 2018 workshop in Amsterdam, to which I have invited @alexandermendes in person or by Skype, and would be more than delighted if Alex would present on LibCrowds and show the tag demo in that context. If the functionality development took longer, we have a final demo opportunity at the Digital Humanities Congress 23018, in Sheffield, in early September, at which I am presenting a co-authored paper with Dr Mark Hailwood (Bristol), again about IIIF enablement. Glen Robson, IIIF technical coordinator, is showing a keen interest in our initiative, and may be Skyping into our Amstrdam workshop.

_Medium term/longer term_

- We could partner to build LibCrowds into the Signs of Literacy initiative as its core crowd sourcing platform. This would encourage exposure of the LibCrowds platform to multiple GLAM institutions, researchers and the General Public.

- Chronoscopic Education/Signs of Literacy would explicitly raise money to support British Library development costs, infrastructure costs, overhead and other costs related to any such partnership.

**Brief context**

- Colin Greenstreet is giving a paper at IIIF conference in Washington DC, May 21-25. Title: Creating an IIIF/Transkribus enabled manuscript community to explore C17th literacy. One key topic from our abstract is "We are exploring the potential of IIIF standards, viewers and annotation tools to support our vision. We are developing an IIIF demo of manifests for markes, initials and signatures from multiple IIIF image servers (e.g. by occupation, type, year range), which we will use with historians and computer scientists as the starting point for a robust, flexible spec."

- It is our intention to show a mock-up at the conference of the functionality we envisage for IIIF manifests of markes, initials and signatures. We do not have the funding to create a real demo for the conference, so at the moment our intention is to a dummy, static, demo using "storyboards".

- We (the Signs of Literacy community initiative for research into historical literacy, sponsored by Chronoscopic Education, MarineLives and Dr Mark Hailwood (Bristol), and intending to add further community partners) are spending April-December 2018 developing our vision for technology enablement for research into historical literacy. At the same time we are seeking to generate technical, GLAM and research interest (historians, linguists), and potential funder interest in Signs of Literacy. We plan multiple grant bids in 1H 2019, rather than one huge grant bid. This will enable individual GLAM institutions in the community to pair up with researchers to pursue topics of particular interest to them, under an overall umbrella and community governance.

- Driving our initiative is [a vision of using pattern recognition and machine learning at scale](https://github.com/Signsofliteracy/Signoff/blob/master/MarineLives_Turing-Accenture%20DSG%20science%20challenges_DEFINITIVE_THREE_12022018.pdf) (absolute minimum of 50,000 marke, initials and signature images, but it could be in the hundreds of thousands). We are working with the Alan Turing Institute to develop our proposal further, and are likely to bring in additional machine learning experts from Bristol and the Netherlands.

- Our scope is comparative, with the initial focus on data from England and the Netherlands, with the English data being English High Court of Admiralty depositions (HCA 13), sourced from the TNA/MarineLives, and the Dutch data sourced from the Alle Amsterdamser Akten (the Amstrdam notarial archives, a UNESCO rated resource which is being mass digitised with Mondrian Stichting funding, but with the approach and governance designed to allow the addition of countries and GLAM institutions.

- We are running a half day workshop on Tuesday, June 5th, 2018, hosted by Mark Ponte of the Stadsarchief Amsterdam, who is a member of the Alle Amsterdamser Akten core project team. This workshop, which is by invitation and has maximum capacity of 24, is attracting considerable interest from technical and content researchers. For example, Dr Rainer Simon, technical director of the Recogito/Pelagios Community initiative, Dr Marieke van Erp, the new head of the Digital Humanities Lab  at the KNAW Humanities Clustre (Huygens ING, IISH and Meertens Institute) and Dr Jelle van Louuttum, a senior maritime & economic historian at the Meertens Institute.

- The workshop is designed to examine technology tools to support historical literacy research, and will examine the potential of IIIF, Transkribus and Recogito to enable and contribute to this, and will drill down into the potential for pattern recognition and machine learning in historical literacy research.

- Core to our plans will be to create large scale training data sets and control data sets. Both data sets will require large scale markup of images, both regions on the images containing markes, initials and signatures, and regions on the images containing metadata for person name, occupation, place of residence and date of deposition.

- Core to our plans is also the use of crowdsourcing to tag and/or annotate the training and control data sets. Hence our strong interest in LibCrowds as a IIIF compliant crowdsourcing platform with a strong development team and multiple use cases from catalogues to playbills.

**Comment by alexandermendes** [comment]
Hi @Addaci, I'm waiting to have a conversation about this internally when people are back in the office, so apologies for the slow reply, I will get back to this!

**Comment by Addaci** [comment]
@alexandermendes @mialondon Many thanks for this further response. Fully understand resource issues. The collaboration idea(s) is a medium to long term idea, kicking off in 2019, and would include funding from Chronoscopic Education (which is  applying end May 2018 for charitable incorporated status). In the short term,  we have tech constraints. Potentially, as a favour, I could ask @Rainersimon, lead developer at Pelagios Commons if he could help us install a IIIF server - presumably we need an annotation server as well. Or I caould pay Digirati to do this. I could even try Klokan Technologies to see if they would help, presumably again paid. Ideal, though, since I only want to do a tiny demo (max 40 images), would be to be able to use a collection microsite - I would put up (say) twenty English High Court o Admiralty images and twenty Alle Amsterdamser Aketen (Amsterdam notarial archives) images, and show the functionality in principal. I would ideally demo this at the IIIF conference in Washington, May 21-25, 2018, with full credit to LibCrowds. If that timing is too quick, I would demo it for the first time at our June 5th workshop at the Stadsarchief Amsterdam. I am at early stage of getting the Huygens ING institute and the Digital Humanities Lab KNAW Humanities Cluster interested in collaboration in 2019 in one or more projects to be structured and grant money to be raised under the Signs Of Literacy umbrealla, and I am sure they would also be interested in this tag driven IIIF manifest functionality

**Comment by alexandermendes** [comment]
Minor update - have been thinking about this for the past few days and I think we're going to settle on a relatively simple solution for our tagging system. Too much going on at the moment to go into this in any huge depth but we should be able to come up with the start of something interesting.

Our user tags will be sent to a Web Annotations server with something like the structure below:

```json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "motivation": "tagging",
  "type": "Annotation",
  "body": {
    "type": "TextualBody",
    "value": "foo",
    "format": "text/plain"
  },
  "target": [
    {
      "source": "https://api.bl.uk/image/iiif/ark:/81055/vdc_100022589157.0x000003/full/max/0/default.jpg",
      "type": "Image",
      "scope": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x000002/manifest.json",
      "renderedVia": {
        "id": "https://api.bl.uk/image/iiif",
        "type": "Software",
        "schema:softwareVersion": "2.0"
      }
    },
    {
      "source": "https://api.bl.uk/image/iiif/ark:/81055/vdc_100022589157.0x000004/full/max/0/default.jpg",
      "type": "Image",
      "scope": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x000002/manifest.json",
      "renderedVia": {
        "id": "https://api.bl.uk/image/iiif",
        "type": "Software",
        "schema:softwareVersion": "2.0"
      }
    }
  ]
}
```

Each target links to the image itself as we also want to use this for images not served from a IIIF Image API service (we also have projects using Flickr images). However, to help identify those that do have an associated image server we add some details of that server in the `renderedVia` section (I still need to choose a suitable tag that already exists as part of the context to identify the [compliance level](http://iiif.io/api/image/2.1/compliance/)).

We then take the IRI for one of these annotations and use it to iterate over the targets and generate a basic manifest, probably using [iiif-prezi](https://github.com/iiif-prezi/iiif-prezi). The manifest for each item is in there as the `scope` so we can later decide how we might want to go back and handle the metadata of the original items.

**Comment by Addaci** [comment]
Fully understand, but hope the two of you will stay in touch as I attempt
to pull IIIF, Pelagios/Recogito and Transkribus closer together.

Plus the new game in town is Google, having persuaded Google owned Kaggle
to run on a pro bono basis a Signs of Literacy Kaggle Research Competition,
Nov 2018-mid-Jan 2019. I am pitching to Google that they should help me
pull these ecosystems closer together around Signs of Literacy as a use
case, off the back of the Kaggle competition.

Would love to have some British Library involvement in this

https://www.linkedin.com/pulse/proposed-signs-literacy-kaggle-research-competition-2018-greenstreet/

Colin

**Comment by mialondon** [comment]
@alexandermendes a quick reminder to fix the markdown issue for the tagging link text!

**Comment by alexandermendes** [comment]
Use a hyphen, there is an explanation of this in the modal!

**Comment by alexandermendes** [comment]
There is a reason for this. Using spaces in PostgreSQL full-text searches complicates things as the queries operate on a [per-token basis](https://www.postgresql.org/docs/9.5/static/textsearch-intro.html#TEXTSEARCH-MATCHING). It is possible to run phrase searches but that would probably require creation of a separate API endpoint. Could go into this further but basically this is the simplest way to handle multi-word tags without creating a bunch of extra work!

**Comment by mialondon** [comment]
Ah! We'll need to tweak that text so the most important information is first. I stopped reading somewhere around 'programmatic research purposes'.

**Comment by mialondon** [comment]
@alexandermendes is it forcing tags to lower-case? That's inappropriate when you're tagging place names or personal names (actors, cities, etc)

**Comment by alexandermendes** [comment]
Not actually a totally straightforward solution here. So, do we store "english", "English" and "ENGLISH" as separate tags? 

When the user goes to the browse page and types in "eng" they will see all of these options in the dropdown box, which do they select? And are they then shown items tagged as "english" and not as "English"? Or, do we normalise them in some way and if it's not into lowercase how do we normalise?

**Comment by mialondon** [comment]
@alexandermendes title case, as elsewhere?

**Comment by alexandermendes** [comment]
Ok, will change all tags to title case
