### ISSUE TITLE
Date transcription task missing specialised help

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#663]
Not sure if it's just this project missing it, or we haven't made one yet: https://www.libcrowds.com/collection/playbills/projects/82/iiif-annotation

An animation showing zooming into the date might be a good way to show off functionality while making it clear it's not a title transcription task (it's easy to get into the wrong zone!) and also provide a place to remind people not to use US-style dates and to just record what they can if there's no year.

**Comment by alexandermendes** [comment]
Will add the content label as this is really a use of the application rather than a code fix. I would also like to switch over to the version visible on the dev server ASAP. The documentation contains guidance on how to update those tutorials.

https://dev.libcrowds.com/collection/playbills/projects/82/iiif-annotation

**Comment by alexandermendes** [comment]
Should find that this is fixed now - the tutorials all come from the templates now rather than individual projects - close when ready!

**Comment by mialondon** [comment]
Hoorah!
